### ISSUE TITLE
Uncaught TypeError: Cannot read property 'status' of null

### ISSUE THREAD

**Issue by croudsky1977** [cliffrowley/atom-circle-ci#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.3
**Thrown From**: [circle-ci](https://github.com/cliffrowley/atom-circle-ci) package, v0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'status' of null

```
At /Users/croudsky/.atom/packages/circle-ci/lib/circle-ci-status-view.coffee:52

TypeError: Cannot read property 'status' of null
  at /Users/croudsky/.atom/packages/circle-ci/lib/circle-ci-status-view.coffee:52:18
  at /Users/croudsky/.atom/packages/circle-ci/lib/circle-ci-client.coffee:61:15
  at IncomingMessage.<anonymous> (/Users/croudsky/.atom/packages/circle-ci/node_modules/node-rest-client/lib/node-rest-client.js:425:9)
  at IncomingMessage.emit (events.js:138:20)
  at _stream_readable.js:909:16
  at process._tickCallback (node.js:366:11)

```

### Commands

```
     -1:11.1 core:backspace (atom-text-editor.editor.is-focused)
  4x -1:10.6 core:move-down (atom-text-editor.editor.is-focused)
     -1:09.4 core:move-up (atom-text-editor.editor.is-focused)
     -1:09.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:08.5 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.7 core:save (atom-text-editor.editor.is-focused)
     -0:11.5 feedback:show (feedback-status)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "atom-lint",
      "linter",
      "term2",
      "symbols-view",
      "pane-move-plus"
    ],
    "themes": [
      "itg-dark-ui",
      "itg-dark-syntax"
    ]
  },
  "circle-ci": {
    "iconColor": true,
    "apiToken": "20ee600984f502c291515a442db079b3ecc4cc67"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
ScssBundle, v0.4.0
Stylus, v0.6.2
Sublime-Style-Column-Selection, v1.2.3
angularjs, v0.2.0
angularjs-styleguide-snippets, v0.6.0
atom-angularjs, v0.1.2
atom-backbone, v0.6.0
atom-beautify, v0.23.1
atom-color-highlight, v3.0.8
atom-grunt-configs, v0.1.0
atom-jade, v0.1.0
atom-runner, v2.3.0
autocomplete-emojis, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-snippets, v1.2.0
circle-ci, v0.7.1
compass, v0.7.5
composer, v0.3.1
css-color-highlight, v0.3.0
css-color-highlighting, v0.2.4
cucumber, v0.4.1
dash, v1.1.0
editorconfig, v0.3.3
file-icons, v1.5.2
file-type-icons, v0.5.4
file-types, v0.3.0
git-log, v0.3.0
grunt-runner, v0.8.0
gulp-snippets, v0.6.1
highlight-column, v0.4.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
ionic-atom, v0.3.1
itg-dark-syntax, v0.3.0
itg-dark-ui, v0.2.0
japanese-wrap, v0.2.4
language-SCSS, v0.2.0
language-actionscript, v0.1.0
language-actionscript3, v0.2.0
language-coffee-script-angular, v2.2.0
language-docker, v1.1.3
language-dockerfile, v0.1.0
language-haml, v0.17.0
language-jade, v0.3.0
language-rspec, v0.3.0
language-stylus, v0.1.0
language-swift, v0.3.0
language-typed-coffee-script, v0.1.0
linter-coffeelint, v0.2.0
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-haml, v0.1.1
linter-htmlhint, v0.0.10
linter-jshint, v0.1.0
linter-rubocop, v0.2.2
local-history, v2.2.2
localization, v1.16.1
minifier, v0.2.0
open-last-project, v0.3.5
project-manager, v1.15.5
react, v0.10.1
recent-files, v0.3.0
recent-projects, v0.3.0
regex-railroad-diagram, v0.7.1
sassbeautify, v0.2.0
script, v2.18.0
terminal-panel, v1.10.0
underscorejs-snippets, v0.2.2
web-view, v0.3.0
wercker-status, v0.3.0

# Dev
No dev packages
```

**Comment by hd-deman** [comment]
same :hankey:

**Comment by nj** [comment]
Was experienced this here too as the screen was totally filled, in relation to CircleCI was down before due to a GitHub issue.

In additional, it didn't help disabling the plugin (without restarting), as it kept "spamming".

Might be a good idea to handle this, have fallback for status `503` (*Service unavailable*) which can easily occur every now and then.

**Comment by tiwilliam** [comment]
Experience the same shit storm, I'll upload a new version that probably fixes this.
