### ISSUE TITLE
Failed to activate the circle-ci package

### ISSUE THREAD

**Issue by iconnor** [cliffrowley/atom-circle-ci#20]
Steps to reproduce:

1. Open Atom and get the warning

![image](https://cloud.githubusercontent.com/assets/22875/7414678/155fcb7c-ef09-11e4-9e04-f875991900f2.png)

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [circle-ci](https://github.com/cliffrowley/atom-circle-ci) package, v0.8.0

### Stack Trace

Failed to activate the circle-ci package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.activate (/Users/iconnor/.atom/packages/circle-ci/lib/circle-ci.coffee:19:30)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
circle-ci, v0.8.0
language-csharp, v0.5.0
language-emblem, v0.1.0
minimap, v4.8.0
pretty-json, v0.3.3
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by tiwilliam** [comment]
Fixed in 0.10.0.
