### ISSUE TITLE
Uncaught Error: Repository has been destroyed

### ISSUE THREAD

**Issue by drazisil** [cliffrowley/atom-circle-ci#25]
[Enter steps to reproduce below:]

1. Delete branch?
2. Remove project folder so there are no projects open

**Atom Version**: 1.1.0
**System**: Debian GNU/Linux
**Thrown From**: [circle-ci](https://github.com/cliffrowley/atom-circle-ci) package, v0.10.1

### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /usr/share/atom/resources/app.asar/src/git-repository.js:377

Error: Repository has been destroyed
  at GitRepository.module.exports.GitRepository.getRepo (/usr/share/atom/resources/app.asar/src/git-repository.js:377:15)
  at GitRepository.module.exports.GitRepository.getConfigValue (/usr/share/atom/resources/app.asar/src/git-repository.js:191:19)
  at GitRepository.module.exports.GitRepository.getOriginURL (/usr/share/atom/resources/app.asar/src/git-repository.js:195:19)
  at CircleCiStatusView.module.exports.CircleCiStatusView.fetchBuildArray (/home/drazisil/.atom/packages/circle-ci/lib/circle-ci-status-view.coffee:49:19)
  at /home/drazisil/.atom/packages/circle-ci/lib/circle-ci-status-view.coffee:74:10

```

### Commands

```
  2x -0:30.3.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "code-macro"
    ],
    "projectHome": "~/dev",
    "autoHideMenuBar": true
  },
  "circle-ci": {
    "apiToken": "ce602976b865efec49fa8a6b260b86904cfb1d8f",
    "iconColor": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.16
circle-ci, v0.10.1
code-macro, v0.1.0
git-plus, v5.5.4
js-refactor, v0.6.0
linter, v1.10.0
linter-js-standard, v3.2.1
refactor, v0.6.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by cliffrowley** [comment]
Thanks for this, whilst I'm not using Circle CI myself currently and so won't be working on this @tiwilliam may be able to jump in :-)

Failing that, do feel free to submit a PR if you have time/inclination!
